### PR TITLE
Adds support for the config-file element used by cordova-custom-config.

### PR DESCRIPTION
**Pull request by idpaterson**
[cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) allows modification of the *-Info.plist and AndroidManifest.xml configuration files to cover cases where a cordova plugin may not exist for the settings you need. Since both of these files are XML-formatted, the module simply takes the content of the <config-file> element and inserts into the appropriate file as directed.

Unfortunately, js2xmlparser does not allow blocks of XML as strings, so in order to support this in grunt-cordova-config it is necessary to write the config in js2xmlparser-compatible JSON. This is a challenge, but can be done, at least [well enough](https://github.com/michaelkourlas/node-js2xmlparser/issues/34).

Lacks README documentation and examples since I am unsure whether this functionality will be acceptable and useful for others. I will gladly finish that up if this addition is useful for others.

**NOTE** the tests will fail for an unrelated reason: the current test process assumes that the config keys will be iterated in the order specified. After adding the additional config, the objects specified in the Gruntfile no longer preserve key order. I am not sure how to approach that issue.

### CODE REVIEW

**Comment by idpaterson** [comment]
Alternatively, the tests *will* pass. I suppose that key order may be system-dependent.

I am currently using this to support a display name on iOS. I do not understand how Cordova decided to use a single `name` property for the display name, project name, executable name, etc. If that name is ever changed the app will have incompatible binaries, duplicate plists, etc.
```json
"configFiles": [
	{
		"target": "<%= name %>-Info.plist",
		"parent": "CFBundleDisplayName",
		"contents": {
			"string": "<%= displayName %>"
		}
	}
]
```

I was not able to simply add a `Localizable.strings` file because it would have to be imported into the Xcode project file which is not so easy in an automated build setup. It looks like [node-xcode](https://github.com/alunny/node-xcode) may have been able to do that for me, which would be a better solution if it works since multiple languages would be supported.

**Comment by shustariov-andrey** [comment]
Thanks for PL, first of all.

Tests used to fail because of problem you mentioned in the past, when node-unit was used as test framework. Now mocha and chai are used ant that should not be a problem any more.

I don't see why it can't be useful. It doesn't break any existing functionallity, and you've already pointed at least 2 use cases)

So, please, finish it up and I'll merge and make new release soon.

**Comment by idpaterson** [comment]
Thanks, I will wrap this up.

**Comment by idpaterson** [comment]
Added the documentation, quite a nice experience working with this project - I love the rewrite, @kkirby and @shustariov-andrey. I am not happy with the following as it modifies the config file data:
```
contents['@'] = {
	target,
	parent
};
```
It may be that the `contents` data is already a copy of the original, I just don't like modifying objects like that without knowing what else may use the same reference. 

I would prefer to use `Object.assign({}, contents, {'@': {target, parent}})` but I could not get it to work in Babel 5 (Object.assign was passed through as-is). I briefly tried upgrading the project to Babel 6 (because babel-plugin-transform-object-assign is not compatible with version 5) but that seemed to involve a lot of work well beyond the scope of this issue.

**Comment by kkirby** [comment]
@idpaterson You should be able to do something like this:

```javascript
return {
	'@': {
		target,
		parent
	},
	...contents
};
```

Though I haven't tested it.

**Comment by idpaterson** [comment]
Thanks, I tried spread syntax but Babel left it as-is. However, I deleted the compiled lib directory and ran it again and Babel properly substituted it with `_.extend`, so that works for me. I think I may have had some outdated node modules from forking quite some time ago.

**Comment by idpaterson** [comment]
Travis wasn't thrilled with that. Seems that JSHint does not support es7 syntax yet. The upcoming JSHint version 3 [will support](http://jshint.com/blog/new-lang-features/) Stage 2 and higher es7 syntax. Is there any other syntax that can get Babel 5 to include the lodash extend function? I'm finding it very difficult to follow the documentation on Babel 5.

**Comment by shustariov-andrey** [comment]
I think, you can add jshint ignore comment for now, like the following:

```javascript
return {
  '@': {
    target,
    parent
  },
  /* jshint ignore:start */
  ...contents
  /* jshint ignore:end */
};
```
I will try to find some solution to this problem later.

**Comment by idpaterson** [comment]
Okay, if you're fine with that I can make the change. Seems some people go with alternatives for jshint like babel-eslint since the JSHint team does not agree with the practice of using language features that are not fairly well-standardized.

**Comment by idpaterson** [comment]
This ends up with the following at the tail of the processed file in `lib/`... I'm going to withhold that and allow you to make any changes necessary to linting.
```js
/* jshint ignore:start */

/* jshint ignore:end */
```

**Pull request merged**
